[package]
name = "ammonia"
version = "0.6.1"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "HTML Sanitization"
keywords = [ "sanitization", "html" ]
license = "MIT / Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/ammonia/"
repository = "https://github.com/notriddle/ammonia"

[dependencies]
html5ever = "0.19"
maplit = "0.1"
tendril = "0.4"
url = "1.4"
lazy_static = "0.2"
